version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: perfex_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  www:
    image: php:8.1-apache-buster
    volumes:
      - "./perfex_crm/:/var/www/html"
    ports:
      - 80:80
    
